# -*- coding: utf-8 -*-
"""Order-separated truncation error: eps-exponent of each cumulant rate.

Rationale
---------
The loss rate is K_t(k) = sum_{m>=1} (dot kappa_m / m!) (i k)^m, so truncating at
order n discards exactly the terms dot kappa_m with m > n. The parity of i^m puts
even orders in the real part and odd orders in the imaginary part, so
order-separation is directly testable: measure the eps-exponent of each dot
kappa_m and check whether odd and even orders differ, with odd orders lower.

Two initial-state families (the key contrast)
---------------------------------------------
The families differ only in which order is nonzero initially:
  family A  kappa_4(0)=0, only skewness nonzero  -> even orders are generated by
            the dynamics alone
  family B  kappa_4(0)!=0                        -> even orders are set initially
Expectation: the odd-order exponent is unchanged (set by the nonlinearity) while
the even-order exponent changes with the family.

Setup
-----
1D rule with fixed nodes {-2,-1,0,1,2} and weights solving a 5x5 linear system to
match mu0=1, mu1=0, mu2=1, mu3=gamma, mu4=3+kurt4 exactly. Scale Sigma0 = eps^2 I,
with the cloud centered at a point on the attractor (the origin is unusable: it is
an unstable fixed point where lambda_1 = 11.8, so the cloud is amplified by two
orders of magnitude and the exponent is entirely distorted). dot kappa uses central
differences to avoid the O(h) bias of a first difference.

Output: results/E07_orders.json
"""
import os
import sys

import numpy as np

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
import n01_common as C

EPS_LIST = [0.02, 0.05, 0.1, 0.2, 0.4]
GAMMA = 0.5
FAMILIES = [("k3only", 0.5, 0.0), ("k3k4", 0.5, -1.0)]
T = 0.5
H_DER = 0.02
H_INT = 0.001
NODES = np.array([-2.0, -1.0, 0.0, 1.0, 2.0])


def asym_rule_1d(gamma, kurt4=0.0):
    """Fixed nodes; weights solve a linear system matching the first four moments exactly."""
    A = np.array([[q ** k for q in NODES] for k in range(5)], dtype=float)
    m = np.array([1.0, 0.0, 1.0, gamma, 3.0 + kurt4])
    w = np.linalg.solve(A, m)
    assert np.all(w > -1e-12), ("negative weight, parameters out of range", gamma, kurt4, w)
    return NODES.copy(), w


def check_rule(gamma, kurt4):
    nd, w = asym_rule_1d(gamma, kurt4)
    return [float(np.sum(w * nd ** k)) for k in range(5)]


def cumulants_1d(X, W, axis=0):
    """1D cumulants kappa_1 .. kappa_5 of the weighted samples along the axis component."""
    q = X[:, axis]
    w = W / W.sum()
    m1 = float(np.sum(w * q))
    d = q - m1
    m2 = float(np.sum(w * d ** 2))
    m3 = float(np.sum(w * d ** 3))
    m4 = float(np.sum(w * d ** 4))
    m5 = float(np.sum(w * d ** 5))
    return np.array([m1, m2, m3, m4 - 3.0 * m2 ** 2, m5 - 10.0 * m3 * m2])


def integrate_cloud(X, T, h=H_INT):
    x = X.copy()
    for _ in range(int(round(T / h))):
        x = C.rk4(x, 0.0, h)
    return x


_MU0 = None


def attractor_point(T_relax=20.0, h=0.002):
    """Cloud center as a point on the attractor. The origin is an unstable fixed point (lambda_1=11.8) and is unusable."""
    x = np.array([1.0, 1.0, 1.0])
    for _ in range(int(round(T_relax / h))):
        x = C.rk4(x, 0.0, h)
    return x


def run(eps, gamma, kurt4, T=T, hd=H_DER):
    global _MU0
    if _MU0 is None:
        _MU0 = attractor_point()
    nodes, weights = asym_rule_1d(gamma, kurt4)
    X, W = C.build_cloud(nodes, weights, (eps ** 2) * np.eye(3), mean=_MU0)

    km = cumulants_1d(integrate_cloud(X, T - hd), W)
    k0 = cumulants_1d(integrate_cloud(X, T), W)
    kp = cumulants_1d(integrate_cloud(X, T + hd), W)
    dk = (kp - km) / (2.0 * hd)
    return dict(eps=eps, kappa=k0, dkappa=dk)


def fit_power(eps, y):
    e = np.log(np.array(eps, dtype=float))
    v = np.log(np.abs(np.array(y, dtype=float)))
    ok = np.isfinite(v)
    A = np.vstack([e[ok], np.ones(ok.sum())]).T
    p, _ = np.linalg.lstsq(A, v[ok], rcond=None)[0]
    return float(p)


def main():
    print("=== rule check (mu0..mu4) ===")
    for name, g, k4 in FAMILIES:
        print("  %-8s gamma=%.2f kurt4=%+.1f -> %s"
              % (name, g, k4, ["%.6f" % v for v in check_rule(g, k4)]))

    out = {"meta": dict(gamma=GAMMA, T=T, h_der=H_DER, h_int=H_INT, eps=EPS_LIST,
                        families=[f[0] for f in FAMILIES],
                        nodes=NODES.tolist()),
           "families": {}}

    for name, g, k4 in FAMILIES:
        cases = []
        for eps in EPS_LIST:
            r = run(eps, g, k4)
            cases.append(dict(eps=eps,
                              kappa=[float(v) for v in r["kappa"]],
                              dkappa=[float(v) for v in r["dkappa"]]))
        pw = {}
        for m in (2, 3, 4, 5):
            pw["kappa%d" % m] = fit_power(EPS_LIST, [c["kappa"][m - 1] for c in cases])
            pw["dkappa%d" % m] = fit_power(EPS_LIST, [c["dkappa"][m - 1] for c in cases])
        out["families"][name] = dict(gamma=g, kurt4=k4, cases=cases, powers=pw)

        print("\n--- %s (gamma=%.2f, kurt4=%+.1f) ---" % (name, g, k4))
        for m in (2, 3, 4, 5):
            tag = "even" if m % 2 == 0 else "odd"
            print("  %s  kappa_%d power %+7.4f   |  dot kappa_%d power %+7.4f"
                  % (tag, m, pw["kappa%d" % m], m, pw["dkappa%d" % m]))

    C.save_json("E07_orders.json", out)

    print("\n=== criterion ===")
    for name in out["families"]:
        p3 = out["families"][name]["powers"]["dkappa3"]
        p4 = out["families"][name]["powers"]["dkappa4"]
        print("  %-8s  odd branch dot kappa_3 ~ eps^%.2f , even branch dot kappa_4 ~ eps^%.2f "
              "-> odd branch leads by %+.2f powers" % (name, p3, p4, p4 - p3))


if __name__ == "__main__":
    main()
