# -*- coding: utf-8 -*-
"""Cross-system reproduction of mechanism 1: does order-separation with odd-order lead hold beyond Lorenz-63?

Design (same measurement convention as E07, only the system changes)
-------------------------------------------------------------------
1. Initial clouds use the same 1D 5-node rule as E07 (fixed nodes {-2,-1,0,1,2},
   weights solving a linear system to match mu0=1, mu1=0, mu2=1, mu3=gamma,
   mu4=3+kurt4), tensor-producted into a d-dimensional cloud with covariance
   exactly eps^2 I and no sampling noise.
2. The cloud center is a point on the attractor (the origin is unusable: it is
   usually an unstable fixed point and fully distorts the exponent).
3. dot kappa_m uses central differences (T±h_der) to avoid the O(h) bias of a
   first difference.
4. The integration time T is not a free parameter. Each system's T is set so that
   the linear amplification factor (cloud-spread growth) matches that of L63 at
   T=0.5, so all systems are compared at equal dynamical amplification.

Systems
-------
L63      : standard Lorenz-63 (reference; must reproduce E07)
Rossler  : phase-coherent spiral chaos, topologically different from L63 (no
           saddle-type folding)
L96      : Lorenz-96, N=5, only quadratic nonlinearity, high-dimensional ring
           coupling

Three initial-state families (differing only in which order is nonzero initially)
  gauss  gamma=0   kurt4=0   -> third and fourth orders zero, all non-Gaussianity
                                generated by the dynamics
  k3only gamma=0.5 kurt4=0   -> only skewness nonzero
  k3k4   gamma=0.5 kurt4=-1  -> kurtosis also nonzero

Output: results/E08_crosssystem.json
"""
import os
import sys

import numpy as np

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
import n01_common as C

NODES = np.array([-2.0, -1.0, 0.0, 1.0, 2.0])
FAMILIES = [("gauss", 0.0, 0.0), ("k3only", 0.5, 0.0), ("k3k4", 0.5, -1.0)]
EPS_LIST = [0.02, 0.05, 0.1, 0.2, 0.4]
H_DER = 0.02                      # central-difference step (time)
REF_T = 0.5                       # reference measurement time for L63
EPS_CAL = 1e-3                    # small perturbation used to calibrate the growth factor


# ------------------------------------------------------------------ Systems
def f_l63(x):
    return np.stack([10.0 * (x[..., 1] - x[..., 0]),
                     x[..., 0] * (28.0 - x[..., 2]) - x[..., 1],
                     x[..., 0] * x[..., 1] - (8.0 / 3.0) * x[..., 2]], axis=-1)


def f_rossler(x):
    a, b, c = 0.2, 0.2, 5.7
    return np.stack([-x[..., 1] - x[..., 2],
                     x[..., 0] + a * x[..., 1],
                     b + x[..., 2] * (x[..., 0] - c)], axis=-1)


def f_l96(x):
    F = 8.0
    xp1 = np.roll(x, -1, axis=-1)     # x_{i+1}
    xm1 = np.roll(x, +1, axis=-1)     # x_{i-1}
    xm2 = np.roll(x, +2, axis=-1)     # x_{i-2}
    return (xp1 - xm2) * xm1 - x + F


SYSTEMS = {
    "L63":     dict(f=f_l63,     d=3, seed=np.array([1.0, 1.0, 1.0]),
                    relax=20.0,   h_relax=0.002, h=0.001, Tmax=2.0,  comp=0),
    "Rossler": dict(f=f_rossler, d=3, seed=np.array([1.0, 1.0, 1.0]),
                    relax=400.0,  h_relax=0.005, h=0.002, Tmax=200.0, comp=0),
    "L96":     dict(f=f_l96,     d=5, seed=np.array([8.0] * 5) + 0.01,
                    relax=20.0,   h_relax=0.002, h=0.002, Tmax=10.0, comp=0),
}


# ------------------------------------------------------------------ Utilities
def rk4(f, x, h):
    k1 = f(x)
    k2 = f(x + 0.5 * h * k1)
    k3 = f(x + 0.5 * h * k2)
    k4 = f(x + h * k3)
    return x + (h / 6.0) * (k1 + 2.0 * k2 + 2.0 * k3 + k4)


def integrate(f, X, T, h):
    x = X.copy()
    for _ in range(int(round(T / h))):
        x = rk4(f, x, h)
    return x


def cloud_1d(nodes, weights, eps, mean, d):
    """d-dimensional tensor-product cloud with covariance exactly eps^2 I."""
    grids = np.meshgrid(*([nodes] * d), indexing="ij")
    pts = np.stack([g.ravel() for g in grids], axis=-1)                # (M,d)
    wg = np.meshgrid(*([weights] * d), indexing="ij")
    W = np.prod(np.stack([g.ravel() for g in wg], axis=-1), axis=-1)
    return pts * eps + mean, W


def asym_rule_1d(gamma, kurt4=0.0):
    A = np.array([[q ** k for q in NODES] for k in range(5)], dtype=float)
    m = np.array([1.0, 0.0, 1.0, gamma, 3.0 + kurt4])
    w = np.linalg.solve(A, m)
    assert np.all(w > -1e-12), ("negative weight, parameters out of range", gamma, kurt4, w)
    return NODES.copy(), w


def cumulants_1d(X, W, c=0):
    q = X[:, c]
    w = W / W.sum()
    m1 = float(np.sum(w * q))
    d = q - m1
    m2 = float(np.sum(w * d ** 2))
    m3 = float(np.sum(w * d ** 3))
    m4 = float(np.sum(w * d ** 4))
    m5 = float(np.sum(w * d ** 5))
    return np.array([m1, m2, m3, m4 - 3.0 * m2 ** 2, m5 - 10.0 * m3 * m2])


def attractor_point(sy, h_relax):
    x = sy["seed"].astype(float).copy()
    for _ in range(int(round(sy["relax"] / h_relax))):
        x = rk4(sy["f"], x, h_relax)
    return x


def spread_ratio(sy, mu0, nodes, weights, T, h):
    """Growth factor of cloud spread relative to the initial value (with a very small eps, essentially linear growth)."""
    X, W = cloud_1d(nodes, weights, EPS_CAL, mu0, sy["d"])
    d0 = np.sqrt(np.mean((X - mu0) ** 2))
    XT = integrate(sy["f"], X, T, h)
    dT = np.sqrt(np.mean((XT - XT.mean(axis=0)) ** 2))
    return float(dT / d0)


def calibrate_T(sy, mu0, nodes, weights, target, dt=0.05):
    """Find T so that the growth factor reaches target (log-linear interpolation), capped at Tmax."""
    h = sy["h"]
    T = dt
    prev_r, prev_T = 1.0, 0.0
    while T <= sy["Tmax"] + 1e-12:
        r = spread_ratio(sy, mu0, nodes, weights, T, h)
        if r >= target:
            # log-linear interpolation (the growth factor is nearly exponential, so interpolating in log is more accurate)
            lr0, lr1 = np.log(max(prev_r, 1e-12)), np.log(max(r, 1e-12))
            lt = np.log(target)
            frac = 0.0 if lr1 == lr0 else (lt - lr0) / (lr1 - lr0)
            return float(prev_T + frac * (T - prev_T)), r, True
        prev_r, prev_T = r, T
        T += dt
    return float(sy["Tmax"]), prev_r, False


def fit_power(eps, y):
    e = np.log(np.array(eps, dtype=float))
    v = np.log(np.abs(np.array(y, dtype=float)))
    ok = np.isfinite(v)
    A = np.vstack([e[ok], np.ones(ok.sum())]).T
    p, _ = np.linalg.lstsq(A, v[ok], rcond=None)[0]
    return float(p)


# ------------------------------------------------------------------ Main
def main():
    print("=== rule check (mu0..mu4) ===")
    for name, g, k4 in FAMILIES:
        nd, w = asym_rule_1d(g, k4)
        print("  %-7s gamma=%+.1f kurt4=%+.1f -> %s"
              % (name, g, k4, ["%.6f" % (np.sum(w * nd ** k)) for k in range(5)]))

    gnodes, gweights = asym_rule_1d(0.0, 0.0)

    out = {"meta": dict(eps=EPS_LIST, h_der=H_DER, ref_T=REF_T,
                        families=[f[0] for f in FAMILIES],
                        nodes=NODES.tolist()), "systems": {}}

    # --- reference growth factor: L63 at T=0.5 ---
    ref_sy = SYSTEMS["L63"]
    ref_mu = attractor_point(ref_sy, ref_sy["h_relax"])
    target = spread_ratio(ref_sy, ref_mu, gnodes, gweights, REF_T, ref_sy["h"])
    print("\n=== reference growth factor (L63 @ T=%.2f) = %.4f ===" % (REF_T, target))

    for sname, sy in SYSTEMS.items():
        mu0 = attractor_point(sy, sy["h_relax"])
        Tcal, rat, ok = calibrate_T(sy, mu0, gnodes, gweights, target)
        print("\n########## %s  (d=%d)  T_cal=%.4f  growth factor=%.4f  %s"
              % (sname, sy["d"], Tcal, rat, "" if ok else "[did not reach target; using Tmax]"))

        sy_out = dict(d=sy["d"], T=Tcal, growth=rat, mu0=mu0.tolist(),
                      reached_target=bool(ok), families={})

        for fname, g, k4 in FAMILIES:
            nd, w = asym_rule_1d(g, k4)
            cases = []
            for eps in EPS_LIST:
                X, W = cloud_1d(nd, w, eps, mu0, sy["d"])
                km = cumulants_1d(integrate(sy["f"], X, Tcal - H_DER, sy["h"]), W, sy["comp"])
                k0 = cumulants_1d(integrate(sy["f"], X, Tcal, sy["h"]), W, sy["comp"])
                kp = cumulants_1d(integrate(sy["f"], X, Tcal + H_DER, sy["h"]), W, sy["comp"])
                dk = (kp - km) / (2.0 * H_DER)
                cases.append(dict(eps=eps,
                                  kappa=[float(v) for v in k0],
                                  dkappa=[float(v) for v in dk]))
            pw = {}
            for m in (2, 3, 4, 5):
                pw["kappa%d" % m] = fit_power(EPS_LIST, [c["kappa"][m - 1] for c in cases])
                pw["dkappa%d" % m] = fit_power(EPS_LIST, [c["dkappa"][m - 1] for c in cases])
            sy_out["families"][fname] = dict(gamma=g, kurt4=k4, cases=cases, powers=pw)
            print("  --- %s ---" % fname)
            for m in (2, 3, 4, 5):
                tag = "even" if m % 2 == 0 else "odd"
                print("    %s  kappa_%d ~ eps^%+7.4f  |  dot kappa_%d ~ eps^%+7.4f"
                      % (tag, m, pw["kappa%d" % m], m, pw["dkappa%d" % m]))
            p3, p4 = pw["dkappa3"], pw["dkappa4"]
            print("    >>> odd branch dot kappa_3 ~ eps^%.2f , even branch dot kappa_4 ~ eps^%.2f "
                  "-> odd branch leads by %+.2f powers" % (p3, p4, p4 - p3))

        out["systems"][sname] = sy_out

    C.save_json("E08_crosssystem.json", out)

    print("\n=== cross-system verdict ===")
    print("  %-9s %-8s %10s %10s %10s" % ("system", "family", "p(odd k3)", "p(even k4)", "odd leads"))
    verdict = []
    for sname in SYSTEMS:
        for fname in out["systems"][sname]["families"]:
            pw = out["systems"][sname]["families"][fname]["powers"]
            p3, p4 = pw["dkappa3"], pw["dkappa4"]
            verdict.append((sname, fname, p3, p4, p4 - p3))
            print("  %-9s %-8s %10.3f %10.3f %+10.3f"
                  % (sname, fname, p3, p4, p4 - p3))
    n_ok = sum(1 for v in verdict if v[4] > 0.5)
    print("\n  %d/%d (system, family) combinations satisfy 'odd branch leads by at least half a power'" % (n_ok, len(verdict)))
    print("  (note: in the gauss family both third and fourth initial values are zero; all non-Gaussianity is generated by the dynamics)")


if __name__ == "__main__":
    main()
