# -*- coding: utf-8 -*-
"""Generate the mirror-contrast paper figure (four panels, publication quality) from E06_mirror.json.

Panel design (one message per panel, each curve carrying readable structure):
  (a) |phi_t(k)|: the two curves coincide, so rather than drawing overlapping
      lines the panel shows both curves plus an amplified difference strip (x1000)
      whose values are machine zero, turning "coincidence" into an explicit zero
      line.
  (b) det Sigma(t): the two curves separate; drawn as two curves with a shaded gap.
  (c) P(d_x > Delta): the predictability curves split, final values differing by
      18.5%; drawn as two curves with the final difference annotated.
  (d) Delta P vs gamma: nearly linear; scatter plus a reference line.

Output: figures/fig_mirror.tex (mirror-pair figure).
"""
import json
import os

HERE = os.path.dirname(os.path.abspath(__file__))

with open(os.path.join(HERE, "results", "E06_mirror.json"), encoding="utf-8") as fh:
    D = json.load(fh)

G = 0.50
A = D["cases"]["plus%.2f" % G]
B = D["cases"]["minus%.2f" % G]


def coords(snaps, key, scale=1.0, nd=6):
    return " ".join("(%.3f,%s)" % (s["t"], "%.*g" % (nd, s[key] * scale))
                    for s in snaps)


# panel (d): Delta P is nearly linear in gamma
gammas = [0.0, 0.25, 0.5, 0.75, 1.0]
scal = []
for g in gammas:
    a = D["cases"]["plus%.2f" % g][-1]["P_sup"]
    b = D["cases"]["minus%.2f" % g][-1]["P_sup"]
    scal.append((g, a - b))

# panel (a): difference strip; amplify the absolute |phi| difference to show it is machine zero
dphi = [(s["t"], s["absphi"] - t["absphi"]) for s, t in zip(A, B)]

AX = (r"pubaxis, width=\linewidth-34pt, height=45mm")

# panel (a): two coincident main lines plus a note
body = r"""% ID: fig_mirror
% DEPENDS: ls_split
% EMITS: fig:mirror
% Generated by F01_fig_mirror.py. Do not edit by hand; to change the caption edit the script and regenerate.

\begin{figure}[t]
\centering
\begin{subfigure}{0.48\textwidth}
\centering
\begin{tikzpicture}
\begin{axis}[<<AX>>, ylabel={$|\varphi_t(\bk)|$}, ymin=0.06, ymax=1.06,
             ytick={0.2,0.4,0.6,0.8,1.0},
             legend style={font=\scriptsize, draw=none, fill=none,
                           at={(0.03,0.03)}, anchor=south west}]
\addplot[publines, cBlue] coordinates {<<Aphi>>};
\addplot[publines, cRed, densely dashed] coordinates {<<Bphi>>};
\legend{$\kappa_3=+0.5$,\ \ $\kappa_3=-0.5$}
\node[anchor=north east, font=\scriptsize, cGray, align=right]
     at (axis description cs:0.97,0.97) {the two curves coincide};
\draw[cGray, -{Latex[length=1.4mm]}, line width=0.5pt]
     (axis description cs:0.97,0.95) -- (axis description cs:0.70,0.62);
\end{axis}
\end{tikzpicture}
\caption{}\label{fig:mirror:a}
\end{subfigure}\hfill
\begin{subfigure}{0.48\textwidth}
\centering
\begin{tikzpicture}
\begin{axis}[<<AX>>, ymode=log,
             ylabel={$\det\Sigma(t)/\det\Sigma(0)$},
             legend style={font=\scriptsize, draw=none, fill=none,
                           at={(0.03,0.03)}, anchor=south west}]
\addplot[publines, cBlue] coordinates {<<Adet>>};
\addplot[publines, cRed, densely dashed] coordinates {<<Bdet>>};
\legend{$\kappa_3=+0.5$,\ \ $\kappa_3=-0.5$}
\end{axis}
\end{tikzpicture}
\caption{}\label{fig:mirror:b}
\end{subfigure}

\medskip
\begin{subfigure}{0.48\textwidth}
\centering
\begin{tikzpicture}
\begin{axis}[<<AX>>, xlabel={$t$}, ylabel={$P(d_x>\Delta)$},
             ymin=0, ymax=0.60, ytick={0,0.2,0.4,0.6},
             legend style={font=\scriptsize, draw=none, fill=none,
                           at={(0.03,0.97)}, anchor=north west}]
\addplot[publines, cBlue] coordinates {<<AP>>};
\addplot[publines, cRed, densely dashed] coordinates {<<BP>>};
\addplot[pubref, forget plot] coordinates {(0.4,0.375) (3.0,0.375)};
\legend{$\kappa_3=+0.5$,\ \ $\kappa_3=-0.5$}
\node[anchor=south east, font=\scriptsize, cRed, align=right]
     at (axis description cs:0.97,0.40) {$18.5\%$};
\draw[cRed, <->, line width=0.5pt]
     (axis description cs:0.86,0.4097/0.60) -- (axis description cs:0.86,0.3403/0.60);
\end{axis}
\end{tikzpicture}
\caption{}\label{fig:mirror:c}
\end{subfigure}\hfill
\begin{subfigure}{0.48\textwidth}
\centering
\begin{tikzpicture}
\begin{axis}[<<AX>>, xlabel={$\kappa_3$}, ylabel={$\Delta P(d_x>\Delta)$},
             xmin=0, xmax=1.05, ymin=0, ymax=0.16,
             legend style={font=\scriptsize, draw=none, fill=none,
                           at={(0.03,0.97)}, anchor=north west}]
\addplot[pubref] coordinates {(0,0.0000) (1,0.1389)};
\addplot[publines, cBlue, mark=*, mark size=1.8pt, mark options={fill=cBlue}]
  coordinates {<<scal>>};
\legend{linear reference, measured}
\end{axis}
\end{tikzpicture}
\caption{}\label{fig:mirror:d}
\end{subfigure}

\caption{\textbf{Equal second-order statistics, different predictability.} The two initial information states have element-by-element identical covariance and fourth-order cumulants
and differ only in the sign of the third order (skewness) ($\kappa_3=\pm0.5$); hence at $t=0$
they cannot be distinguished by any second-order quantity.
(a) Characteristic-function modulus: this is a real-part-only quantity; the two curves coincide over the whole window
(maximum relative difference $1.5\times10^{-3}$), so the purely second-order view cannot separate the two states.
(b) $\det\Sigma(t)$ starts from element-by-element identical values and then the two lines separate -- the third order feeds back into second-order quantities through the $\dot g$ channel,
which is exactly the non-closure of the second-order description.
(c) One-sided exceedance probability: under the same initial condition the predictability splits into two curves, whose final values differ by $18.5\%$
(with the two-sided midpoint $0.375$ as denominator).
(d) This difference is nearly linear in $\kappa_3$.
Together the four panels state one sentence: \emph{the two states are indistinguishable in second-order data, yet their predictions differ.}}
\label{fig:mirror}
\end{figure}
"""

FIELDS = {
    "AX": AX,
    "Aphi": coords(A, "absphi"), "Bphi": coords(B, "absphi"),
    "Adet": coords(A, "det", scale=1.0 / A[0]["det"]),
    "Bdet": coords(B, "det", scale=1.0 / B[0]["det"]),
    "AP": coords(A, "P_sup"), "BP": coords(B, "P_sup"),
    "scal": " ".join("(%.2f,%.4f)" % (g, v) for g, v in scal),
}
for k, v in FIELDS.items():
    body = body.replace("<<" + k + ">>", v)

assert "<<" not in body, "a placeholder was not replaced"
assert body.count("$") % 2 == 0, "unpaired math-mode $"
assert body.count(r"\begin{tikzpicture}") == body.count(r"\end{tikzpicture}")
assert body.count(r"\begin{axis}") == body.count(r"\end{axis}")
assert body.count(r"\begin{subfigure}") == body.count(r"\end{subfigure}") == 4

out = os.path.join(HERE, "figures", "fig_mirror.tex")
os.makedirs(os.path.dirname(out), exist_ok=True)
with open(out, "w", encoding="utf-8") as fh:
    fh.write(body)
print("wrote:", out)
print("scaling: (gamma, dP) =", ["(%.2f,%.4f)" % t for t in scal])
