# -*- coding: utf-8 -*-
"""Generate the mirror-contrast paper figure (four panels, publication quality) from E06_mirror.json.

Panel design (one message per panel, each curve carrying readable structure):
  (a) |phi_t(k)| vs t: the two curves coincide (maximum relative difference 1.7e-3),
      so the second-order view cannot separate the two states.
  (b) |det+ / det- - 1| vs t, log-y: starts at machine zero at t=0 and grows to ~1e-1,
      so the two states agree element by element in the second-order data and diverge
      afterwards.
  (c) P(d_x > Delta) vs t: the predictability curves split, final values differing by
      18.5%.
  (d) Delta P vs gamma: nearly linear; scatter plus a reference line.

The E06 run uses 301 snapshots so that all panels are resolved in time.

Output: figures/fig_mirror.tex (mirror-pair figure).
"""
import json
import os

HERE = os.path.dirname(os.path.abspath(__file__))

with open(os.path.join(HERE, "results", "E06_mirror.json"), encoding="utf-8") as fh:
    D = json.load(fh)

G = 0.50
A = D["cases"]["plus%.2f" % G]
B = D["cases"]["minus%.2f" % G]


def coords(snaps, key, scale=1.0, nd=6, stride=1, per=6):
    """Return a wrapped coordinate list for pgfplots."""
    out, buf = [], []
    for s in snaps[::stride]:
        buf.append("(%.3f,%s)" % (s["t"], "%.*g" % (nd, s[key] * scale)))
        if len(buf) == per:
            out.append(" ".join(buf)); buf = []
    if buf:
        out.append(" ".join(buf))
    return "\n  " + "\n  ".join(out)


# panel (d): Delta P is nearly linear in gamma
gammas = [0.0, 0.25, 0.5, 0.75, 1.0]
scal = []
for g in gammas:
    a = D["cases"]["plus%.2f" % g][-1]["P_sup"]
    b = D["cases"]["minus%.2f" % g][-1]["P_sup"]
    scal.append((g, a - b))

# panel (b): relative difference of the two det Sigma, which starts at machine zero
reldet = [(a["t"], abs(a["det"] / b["det"] - 1.0)) for a, b in zip(A, B)]
max_phi_rel = max(abs(a["absphi"] - b["absphi"]) / abs(a["absphi"])
                  for a, b in zip(A, B))

# panel (c): the exceedance probability is a weighted count over the 125-point
# deterministic cloud, so it is quantized; a short moving average suppresses the
# quantization steps without touching the terminal values (18.5%).
MA_W = 11


def _ma(v, w):
    n = len(v)
    h = w // 2
    return [sum(v[max(0, i - h):min(n, i + h + 1)]) / (min(n, i + h + 1) - max(0, i - h))
            for i in range(n)]


PsA = _ma([a["P_sup"] for a in A], MA_W)
PsB = _ma([b["P_sup"] for b in B], MA_W)
pairsA = [(a["t"], v) for a, v in zip(A, PsA)]
pairsB = [(b["t"], v) for b, v in zip(B, PsB)]

AX = (r"pubaxis, width=\linewidth-34pt, height=45mm")

# panel (a): two coincident main lines plus a note
body = r"""% ID: fig_mirror
% DEPENDS: ls_split
% EMITS: fig:mirror
% Generated by F01_fig_mirror.py. Do not edit by hand; to change the caption edit the script and regenerate.

\begin{figure}[t]
\centering
\begin{subfigure}{0.48\textwidth}
\centering
\begin{tikzpicture}
\begin{axis}[<<AX>>, xlabel={$t$}, ylabel={$|\varphi_t(\bk)|$}, ymin=0.06, ymax=1.06,
             ytick={0.2,0.4,0.6,0.8,1.0},
             legend style={font=\scriptsize, draw=none, fill=none,
                           at={(0.03,0.03)}, anchor=south west}]
\addplot[publines, cBlue] coordinates {<<Aphi>>};
\addplot[publines, cRed, densely dashed] coordinates {<<Bphi>>};
\legend{$\kappa_3=+0.5$,\ \ $\kappa_3=-0.5$}
\node[anchor=north east, font=\scriptsize, cGray, align=right]
     at (axis description cs:0.97,0.97) {the two curves coincide};
\draw[cGray, -{Latex[length=1.4mm]}, line width=0.5pt]
     (axis description cs:0.97,0.95) -- (axis description cs:0.70,0.62);
\end{axis}
\end{tikzpicture}
\caption{}\label{fig:mirror:a}
\end{subfigure}\hfill
\begin{subfigure}{0.48\textwidth}
\centering
\begin{tikzpicture}
\begin{axis}[<<AX>>, ymode=log, xlabel={$t$},
             ylabel={$|\det\Sigma_{+}/\det\Sigma_{-}-1|$},
             ymin=1e-16, ymax=1e0,
             legend style={font=\scriptsize, draw=none, fill=none,
                           at={(0.03,0.97)}, anchor=north west}]
\addplot[cGray, densely dashed] coordinates {(0.000,1e-15) (3.000,1e-15)};
\addplot[publines, cBlue] coordinates {<<RELB>>};
\legend{machine zero, $|\det\Sigma_{+}/\det\Sigma_{-}-1|$}
\end{axis}
\end{tikzpicture}
\caption{}\label{fig:mirror:b}
\end{subfigure}

\medskip
\begin{subfigure}{0.48\textwidth}
\centering
\begin{tikzpicture}
\begin{axis}[<<AX>>, xlabel={$t$}, ylabel={$P(d_x>\Delta)$},
             ymin=0, ymax=0.60, ytick={0,0.2,0.4,0.6},
             legend style={font=\scriptsize, draw=none, fill=none,
                           at={(0.03,0.97)}, anchor=north west}]
\addplot[publines, cBlue] coordinates {<<AP>>};
\addplot[publines, cRed, densely dashed] coordinates {<<BP>>};
\addplot[pubref, forget plot] coordinates {(0.4,0.375) (3.0,0.375)};
\legend{$\kappa_3=+0.5$,\ \ $\kappa_3=-0.5$}
\node[anchor=south east, font=\scriptsize, cRed, align=right]
     at (axis description cs:0.97,0.40) {$18.5\%$};
\draw[cRed, <->, line width=0.5pt]
     (axis description cs:0.86,0.4097/0.60) -- (axis description cs:0.86,0.3403/0.60);
\end{axis}
\end{tikzpicture}
\caption{}\label{fig:mirror:c}
\end{subfigure}\hfill
\begin{subfigure}{0.48\textwidth}
\centering
\begin{tikzpicture}
\begin{axis}[<<AX>>, xlabel={$\kappa_3$}, ylabel={$\Delta P(d_x>\Delta)$},
             xmin=0, xmax=1.05, ymin=0, ymax=0.16,
             legend style={font=\scriptsize, draw=none, fill=none,
                           at={(0.03,0.97)}, anchor=north west}]
\addplot[pubref] coordinates {(0,0.0000) (1,0.1389)};
\addplot[publines, cBlue, mark=*, mark size=1.8pt, mark options={fill=cBlue}]
  coordinates {<<scal>>};
\legend{linear reference, measured}
\end{axis}
\end{tikzpicture}
\caption{}\label{fig:mirror:d}
\end{subfigure}

\caption{\textbf{Equal second-order statistics, different predictability.} The two initial information states have element-by-element identical covariance and fourth-order cumulants
and differ only in the sign of the third order (skewness) ($\kappa_3=\pm0.5$); hence at $t=0$
they cannot be distinguished by any second-order quantity.
(a) Characteristic-function modulus: this is a real-part-only quantity; the two curves coincide over the whole window
(maximum relative difference <<MAXPHI>>), so the purely second-order view cannot separate the two states.
(b) The relative difference of the two $\det\Sigma(t)$: it is a machine zero at $t=0$ -- the two states agree element by element in their second-order data -- and grows to about $10^{-1}$ afterwards;
the third order feeds back into second-order quantities through the $\dot g$ channel, which is exactly the non-closure of the second-order description.
(c) One-sided exceedance probability: under the same initial condition the predictability splits into two curves, whose final values differ by $18.5\%$
(with the two-sided midpoint $0.375$ as denominator); the curves are smoothed over a window of $\Delta t=0.11$ to suppress the quantization of the discrete exceedance count.
(d) This difference is nearly linear in $\kappa_3$.
Together the four panels state one sentence: \emph{the two states are indistinguishable in second-order data, yet their predictions differ.}}
\label{fig:mirror}
\end{figure}
"""

def wrap_pairs(pairs, nd=5, per=6):
    out, buf = [], []
    for t, v in pairs:
        buf.append("(%.3f,%s)" % (t, "%.*g" % (nd, v)))
        if len(buf) == per:
            out.append(" ".join(buf)); buf = []
    if buf:
        out.append(" ".join(buf))
    return "\n  " + "\n  ".join(out)


FIELDS = {
    "AX": AX,
    "Aphi": coords(A, "absphi", stride=3), "Bphi": coords(B, "absphi", stride=3),
    "RELB": wrap_pairs(reldet),
    "AP": wrap_pairs(pairsA[::3]), "BP": wrap_pairs(pairsB[::3]),
    "scal": " ".join("(%.2f,%.4f)" % (g, v) for g, v in scal),
    "MAXPHI": "$%.1f\\times10^{-3}$" % (max_phi_rel * 1e3),
}
for k, v in FIELDS.items():
    body = body.replace("<<" + k + ">>", v)

assert "<<" not in body, "a placeholder was not replaced"
assert body.count("$") % 2 == 0, "unpaired math-mode $"
assert body.count(r"\begin{tikzpicture}") == body.count(r"\end{tikzpicture}")
assert body.count(r"\begin{axis}") == body.count(r"\end{axis}")
assert body.count(r"\begin{subfigure}") == body.count(r"\end{subfigure}") == 4

out = os.path.join(HERE, "figures", "fig_mirror.tex")
os.makedirs(os.path.dirname(out), exist_ok=True)
with open(out, "w", encoding="utf-8") as fh:
    fh.write(body)
print("wrote:", out)
print("scaling: (gamma, dP) =", ["(%.2f,%.4f)" % t for t in scal])
