# -*- coding: utf-8 -*-
"""Generate the cross-system reproduction figure from results/E08_crosssystem.json.

Panels:
  (a) Log-log curves of |dot kappa_m| vs eps for the three systems (gauss family,
      all non-Gaussianity generated by the dynamics). Odd branch solid, even branch
      dashed; color/marker distinguish systems. Each curve is normalized at eps=0.4,
      so slopes are directly comparable.
  (b) Discriminant plot: the (p_odd, p_even) scatter of the nine (system x family)
      combinations. Marker shape encodes the system (bullet L63, square Rossler,
      triangle L96), color encodes the initial-state family (cBlue=gauss,
      cRed=k3only, cGreen=k3k4), and all nine points are drawn. The y=x diagonal is
      a gray dashed line labelled "odd = even". Points above the diagonal mean the
      odd-order exponent is lower, i.e. the odd branch leads at small eps.

Output: figures/fig_crosssystem.tex (cross-system figure).
"""
import json
import os
import sys

import numpy as np

HERE = os.path.dirname(os.path.abspath(__file__))
sys.path.insert(0, HERE)
import n01_common as C

OUT = os.path.join(HERE, "figures", "fig_crosssystem.tex")

MARK = {"L63": "*", "Rossler": "square*", "L96": "triangle*"}
LABEL = {"L63": "L63", "Rossler": r"R\"ossler", "L96": "L96"}
ORDER = ["L63", "Rossler", "L96"]

SYS_COLOR = {"L63": "cBlue", "Rossler": "cGreen", "L96": "cOrange"}
FAM_COLOR = {"gauss": "cBlue", "k3only": "cRed", "k3k4": "cGreen"}
FAM_LABEL = {"gauss": "gauss", "k3only": "only $\\kappa_3$", "k3k4": "$\\kappa_3,\\kappa_4$"}


def fmt(v):
    return ("%.5g" % v)


def main():
    d = C.load_json("E08_crosssystem.json")
    eps = d["meta"]["eps"]

    # ---------- panel (a): gauss-family odd/even branches, three systems ----------
    a_lines = []
    leg_a = []
    for s in ORDER:
        fam = d["systems"][s]["families"]["gauss"]
        for m, dash, mkname in ((3, "", "odd"), (4, "densely dashed", "even")):
            y = np.abs(np.array([c["dkappa"][m - 1] for c in fam["cases"]], dtype=float))
            y = y / y[-1]
            coords = " ".join("(%s,%s)" % (fmt(e), fmt(v)) for e, v in zip(eps, y))
            a_lines.append(
                "\\addplot[%s, %s, mark=%s, mark size=1.4pt, mark options={fill=%s}] "
                "coordinates {%s};"
                % (SYS_COLOR[s], dash or "publines", MARK[s], SYS_COLOR[s], coords))
    leg_a = ",".join(
        ["%s odd" % LABEL[s] for s in ORDER] + ["%s even" % LABEL[s] for s in ORDER])

    # two reference slope lines (odd ~ eps^3, even ~ eps^5) anchored on the plot
    a_ref = []
    for e0, e1, p in ((0.02, 0.4, 3.0), (0.02, 0.4, 5.0)):
        y0, y1 = (e0 / 0.4) ** p, (e1 / 0.4) ** p
        a_ref.append("\\addplot[pubref, forget plot] coordinates {(%s,%s) (%s,%s)};"
                     % (fmt(e0), fmt(y0), fmt(e1), fmt(y1)))

    # ---------- panel (b): the nine (p_odd, p_even) points ----------
    pts = []   # (sys, fam, x, y)
    pmin, pmax = 99.0, -99.0
    for s in ORDER:
        for fname in ("gauss", "k3only", "k3k4"):
            pw = d["systems"][s]["families"][fname]["powers"]
            x, y = pw["dkappa3"], pw["dkappa4"]
            pts.append((s, fname, x, y))
            pmin, pmax = min(pmin, x, y), max(pmax, x, y)
    lo = np.floor(pmin) - 0.2
    hi = np.ceil(pmax) + 0.2

    # plot point by point over (system, family), color encodes family
    b_lines = []
    for s in ORDER:
        for fname in ("gauss", "k3only", "k3k4"):
            sub = [(x, y) for (ss, ff, x, y) in pts if ss == s and ff == fname]
            if not sub:
                continue
            coords = " ".join("(%s,%s)" % (fmt(x), fmt(y)) for x, y in sub)
            b_lines.append(
                "\\addplot[only marks, %s, mark=%s, mark size=2.3pt, "
                "mark options={fill=%s}] coordinates {%s};"
                % (FAM_COLOR[fname], MARK[s], FAM_COLOR[fname], coords))

    gaps = [y - x for _, _, x, y in pts]
    gap_txt = "between $%.2f$ and $%.2f$ powers" % (min(gaps), max(gaps))

    # ---------- assemble ----------
    body = r"""% ID: fig_cross
% DEPENDS: ls_split
% EMITS: fig:cross
% Generated by F02_fig_crosssystem.py. Do not edit by hand; to change the caption edit the script and regenerate.

\begin{figure}[t]
\centering
\begin{subfigure}{0.48\textwidth}
\centering
\begin{tikzpicture}
\begin{axis}[pubaxis, width=\linewidth-34pt, height=50mm, xmode=log, ymode=log,
             xlabel={$\epsilon$}, ylabel={normalized $|\dot\kappa_m|$},
             legend style={font=\scriptsize, draw=none, fill=none,
                           at={(0.03,0.03)}, anchor=south west},
             legend columns=2]
@@A_REF@@
@@A_LINES@@
\legend{@@LEG_A@@}
\end{axis}
\end{tikzpicture}
\caption{}\label{fig:cross:a}
\end{subfigure}\hfill
\begin{subfigure}{0.48\textwidth}
\centering
\begin{tikzpicture}
\begin{axis}[pubaxis, width=\linewidth-34pt, height=50mm,
             xlabel={odd-branch exponent $\mathrm{p}(\dot\kappa_3)$},
             ylabel={even-branch exponent $\mathrm{p}(\dot\kappa_4)$},
             xmin=@@LO@@, xmax=@@HI@@, ymin=@@LO@@, ymax=@@HI@@,
             legend style={font=\scriptsize, draw=none, fill=none,
                           at={(0.03,0.97)}, anchor=north west},
             legend columns=1]
\addplot[pubref] coordinates {(@@LO@@,@@LO@@) (@@HI@@,@@HI@@)};
\node[anchor=north east, font=\scriptsize, cGray]
     at (axis description cs:0.97,0.30) {odd $=$ even};
@@B_LINES@@
\legend{$\bullet$ L63, $\blacksquare$ R\"ossler, $\blacktriangle$ L96}
\end{axis}
\end{tikzpicture}
\caption{}\label{fig:cross:b}
\end{subfigure}

\caption{\textbf{The odd-branch lead reproduces across three systems.} The measurement convention is the same as Fig.~\ref{fig:orders}, only the system changes;
each system's measurement time $T$ is fixed by the same criterion, i.e. so that the cloud-spread growth factor matches that of L63 at $T=0.5$
(L63: $T=0.50$, R\"ossler: $T=10.27$, L96: $T=0.15$).
(a) The gauss family (third and fourth initial values both zero, non-Gaussianity generated entirely by the dynamics):
the odd branch $\dot\kappa_3$ is solid and the even branch $\dot\kappa_4$ dashed;
color and marker distinguish systems ($\bullet$ L63, $\blacksquare$ R\"ossler, $\blacktriangle$ L96);
each curve is normalized at $\epsilon=0.4$, and the gray dashed lines are reference slopes $3$ and $5$.
The two groups of slopes are clearly separated.
(b) \emph{Discriminant plot}: the
$(\mathrm{p}(\dot\kappa_3),\mathrm{p}(\dot\kappa_4))$ scatter of the nine (system $\times$ family) combinations.
Marker shape encodes the system, color encodes the initial-state family (\textcolor{cBlue}{blue}=gauss,
\textcolor{cRed}{red}=only $\kappa_3$, \textcolor{cGreen}{green}=$\kappa_3,\kappa_4$).
All nine points lie above $y=x$, i.e. the odd-branch exponent is uniformly lower and leads at small $\epsilon$
(the lead of each group lies between @@GAP@@).
Among them the ``only $\kappa_3$'' and ``$\kappa_3,\kappa_4$'' classes have very close odd-branch exponents,
so the actual independence of the nine groups is lower than the combination count -- the truly independent variation dimensions are the system and ``whether the initial state contains a fourth-order cumulant''.}
\label{fig:cross}
\end{figure}
"""
    body = body.replace("@@A_REF@@", "\n".join(a_ref))
    body = body.replace("@@A_LINES@@", "\n".join(a_lines))
    body = body.replace("@@LEG_A@@", leg_a)
    body = body.replace("@@B_LINES@@", "\n".join(b_lines))
    body = body.replace("@@LO@@", fmt(lo))
    body = body.replace("@@HI@@", fmt(hi))
    body = body.replace("@@GAP@@", gap_txt)

    assert "@@" not in body, "placeholders not replaced"
    assert body.count("\\begin{axis}") == body.count("\\end{axis}") == 2, "axis not paired"
    assert body.count("$") % 2 == 0, "unpaired math-mode $"
    assert body.count("\\begin{subfigure}") == body.count("\\end{subfigure}") == 2

    os.makedirs(os.path.dirname(OUT), exist_ok=True)
    with open(OUT, "w", encoding="utf-8") as fh:
        fh.write(body)
    print("generated:", os.path.abspath(OUT))
    print("panel (b) nine-group gaps:", ";".join(
        "%s/%s: %+.2f" % (LABEL[s], f, y - x) for s, f, x, y in pts))


if __name__ == "__main__":
    main()
